UpliftGames/wally

wally-registry-backend/src/auth.rs
wally-registry-backend/src/tests/mod.rs

Currently a user either has to have the api key to read, or they can read unauthenticated but it's tricky to publish. This PR adds a new AuthMode which allows read/write access to be split between two separate api keys. The read api key is optional. 
The usual use case for this is allowing public read access but restricting write access so I've also added a test which emulates this use case.

DoubleApiKey Implementation

---

CHANGELOG.md
src/installation.rs

This should fix the issue of installation failing due to not finding the `Packages` folder.
I introduced a one line fix as well as some additional instrumentation that I used while debugging the problem.

Fix 'file not found' on installation

---

src/commands/init.rs

This fixes #12 by converting the full package name to all lowercase letters.

Fix init generating invalid package names

---

src/installation.rs
tests/integration/snapshots/integration__install__transitive_dependency.snap

This fixes #16 by updating the relative path created for linking sibling dependencies.

Fix sibling link path

---

src/package_name.rs

Errors during parsing of package names is confusing, see #13. This PR adds extra info to the errors output so users can understand what went wrong more easily.
Users will now see this when they have an invalid scope
```
failed to parse manifest at path /../../wally.toml
Caused by:
package scope Magnalite in invalid (scopes can only contain lowercase characters, digits and '-') for key `package.name` at line 2 column 8
```
I'm not very happy with this but I'm not sure how else to do it. Ideally we would output multiple layers of anyhow context but this isn't easy to do as the toml parsing is what consumes the anyhow error.

Readable package name parsing errors

---

src/package_name.rs

Currently we set no limit for package names. This PR ensures that packages names don't contain more than 64 characters. This is the same limit crates.io uses and seems reasonable for our use case too. I also added a check for package scope length. Although checking scope length shouldn't be necessary I didn't see much reason to not include it either.

Ensure max length for package name

---

src/package_source/registry.rs

Store the Client in the struct rather than creating a new one per package download.
This is suggested by the [reqwest docs](https://docs.rs/reqwest/0.11.4/reqwest/blocking/fn.get.html) for when multiple http requests are being made.

Reuse Client in Registry when downloading packages

---

Cargo.lock
Cargo.toml
src/auth.rs
src/commands/login.rs
src/commands/logout.rs
src/commands/publish.rs
src/git_util.rs
src/package_index.rs
src/package_source/registry.rs
wally-registry-backend/Cargo.toml
wally-registry-backend/src/auth.rs
wally-registry-backend/src/main.rs

This PR is the implementation of public authentication! It closes issue https://github.com/UpliftGames/wally/issues/8, see that for more info.
This PR:
- Adds support for associating an oauth client id with a registry
- Allows `wally login` to ask for an api key or present an oauth flow if the registry has an oauth client id
- Allows storage of authentication tokens on a per registry basis
- Enables the registry backend to accept oauth tokens as authentication by verifying them against the github api
- Creates `owners.json` files in scopes to track ownership and enable ownership by multiple users (although no command to do so exists yet)

Public Authentication Implementation

---

CHANGELOG.md
src/package_contents.rs

Windows paths are not sanitised before being included in the package zip archives #15. This causes them to be incorrectly extracted when used in a unix environment. This PR changes `\`s to `/`s in these paths so the zip archives remain compatible across both Windows and unix environments.
This fix is somewhat naive and may be susceptible to edge cases. However I don't believe they are edge cases we are likely to run into as we only use relative paths. This also seems to be a known issue in the zip crate as it was accounted for once before but has since, seemingly accidentally, been left out. You can see that issue here https://github.com/zip-rs/zip/issues/253. Hopefully that means this will be addressed in the crate soon so we can then remove our fix.

Fix windows generating invalid zip archives

---

CHANGELOG.md
src/commands/install.rs
src/installation.rs
src/manifest.rs
src/package_source/registry.rs
src/test_package.rs

We want to reduce the number of packages we have in the datamodel, primarily this means keeping only one copy of each package. Some packages in the server realm will depend on shared packages, however due to this optimisation they will be held in separate locations in the datamodel. 
To allow server packages to require shared packages we can generate links which reference across realms. This is notable because we cannot generate these links as relative paths. We also don't know the absolute location of where shared packages are as Rojo manages their location.
In order to know where the shared packages are to generate these cross realm links an additional field has been added to the wally.toml. As an example the wally.toml may look like this.
```toml
[package]
name = "magnalite/my-package" …
```

Generate server->shared cross realm links

---

Cargo.lock
Cargo.toml

On Arch linux based distributions it seems that system's libgit2 is incompatible with git2 crate, so a workaround that git2 has provided is to give an option to compile libgit2 from source while building the project.
If anyone building Wally from source sees the following error `invalid version 0 on git_proxy_options`, they can build the crate using vendored libgit2: `cargo build --features vendored-libgit2`.

Adds vendored-libgit2 feature from git2 library

---

CHANGELOG.md
src/commands/publish.rs
src/package_source/registry.rs
wally-registry-backend/src/auth.rs
wally-registry-backend/src/config.rs
wally-registry-backend/src/error.rs
wally-registry-backend/src/main.rs
wally-registry-backend/src/tests/mod.rs

This PR adds a way to ensure clients interacting with a registry have a minimum Wally cli version. It also changes the way request guards are used so errors can be propagated back as expected.

Enforce minimum wally version

---

CHANGELOG.md
README.md
src/commands/publish.rs
src/manifest.rs
src/test_package.rs
test-projects/private-package/default.project.json
test-projects/private-package/src/init.lua
test-projects/private-package/wally.toml
tests/integration/publish.rs

Add private field to package manifest

---

CHANGELOG.md
README.md
src/commands/login.rs

Implements new arguments for the `wally login` subcommand to facilitate easier login in CI environments.
The previous method for logging in using a GitHub Workflow involved manually copying the contents of the hidden auth file and doing something similar to this:
```yaml
run: |
mkdir -p ~/.wally
echo "$WALLY_AUTH" > ~/.wally/auth.toml
```
The new method only requires a valid auth token to be passed and is more future-proof if the auth file format changes:
```yaml
run: wally login --token "$WALLY_AUTH_TOKEN"
```

Implement manual login parameters for login subcommand

---

wally-registry-backend/Dockerfile

`chown=1000` was running before adding the user `1000`, making it fail if the user did not already exist.
This might be a vendor-specific thing / depend on if the backend is running in docker or another runtime such as podman, testing was done using DigitalOcean's App Platform where the backend fails to run without this fix.

Fix registry backend dockerfile command ordering

---

src/commands/init.rs

Solves #12 by escaping all whitespace with a dash.

Replace all whitespace in a username with a dash

---

Cargo.lock
wally-registry-backend/Cargo.toml
wally-registry-backend/src/main.rs
wally-registry-backend/src/storage/mod.rs
wally-registry-backend/src/storage/s3.rs

This allows the registry backend to be used with other providers than GCP. We have been using this exact implementation in our organization without issues since January (https://github.com/readysetplay/wally/commit/1b4ceef242c6bc15055ebd9ab6e0c30b0ae0e52f) with hosting and storage on DigitalOcean.
S3 storage is configured using the following env variables:
`AWS_REGION_NAME` - Name of the storage region to use such as `us-east-1`
`AWS_REGION_ENDPOINT` - Full url endpoint of the S3 server. Some providers only need this and not the region name, so the region name can be omitted and defaults to the same region as the `rusoto` library that this implementation uses.
Authorization is done using S3 standards and utilities that the `rusoto` library provides.
The implementation is otherwise very …

Implement S3-compatible storage for registry backend

---

wally-registry-frontend/src/types/wally.d.ts

Credit to @OverHash for catching this and showing me the correct way to do it.

Fix improper WallyPackageMetadata type

---

wally-registry-backend/src/search.rs
wally-registry-frontend/src/pages/Package.tsx

This PR aims to remove prerelease checks so they can show up on the website and also ensure we show every version of packages. This may have unintended consequences and require a revert as the version handling logic here is unusually fragile.

Remove prerelease checks

---

wally-registry-backend/src/search.rs
wally-registry-frontend/src/pages/Package.tsx

This reverts commit 3fb7d. As expected this has unintended side effects and we will need to make extra changes to the frontend to handle the extra data it is now given.

Revert "Remove prerelease checks (#124)"

---

Cargo.lock
Cargo.toml
src/commands/install.rs
src/installation.rs
src/package_source.rs
src/package_source/in_memory.rs
src/package_source/registry.rs
src/package_source/test_registry.rs
src/resolution.rs
wally-registry-backend/Cargo.toml
wally-registry-backend/src/main.rs
wally-registry-backend/src/storage/gcs.rs
wally-registry-backend/src/storage/mod.rs

This PR adds support for downloading packages in parallel. It also:
- makes the install cli output more visually pleasing
- removes the mutex on the gcs client as it doesn't seem needed and causes concurrent requests to queue up and responded to serially
- adds moka caching to the download endpoint to reduce latency and accelerate download performance for popular packages

Parallel package install

---

wally-registry-backend/src/main.rs
wally-registry-backend/src/storage/mod.rs
wally-registry-backend/src/storage/s3.rs

This PR brings the S3 storage backend up to parity with the changes to GCP storage in https://github.com/UpliftGames/wally/pull/133
- Removes the unnecessary mutex on the S3 client
- Adds moka caching with configurable cache size

S3 backend storage improvements

---

README.md
wally-registry-frontend/src/pages/Install.mdx

Foreman has been superseded by aftman, we should recommend aftman instead! Brew is also cool and convenient if you're into that and apparently has wally already!

Update installation guide

---

Cargo.lock
Cargo.toml
README.md
src/auth.rs
src/commands/login.rs
src/commands/mod.rs
src/commands/publish.rs
src/package_source/registry.rs
tests/integration/publish.rs

This PR adds the ability to use `wally publish --token "$AUTH_TOKEN"` instead of requiring a `wally login`. It also adds a helper function to make `AuthStore` more convenient and an integration test to ensure publish correctly passes the token to the publish request.

Allow --token to be used in publish

---

wally-registry-frontend/src/pages/Package.tsx

closes #123 
(feels like a slightly silly mistake)

Fix fatal error on package view where no versions contain '-'

---

wally-registry-frontend/src/pages/Package.tsx

When you download a package, the file name ends with the version, so something like `package@1.0.0` would be read by your OS as a `.0` file type, which is obviously not what we wanted.
This fix is as simple as just adding `.zip` to the filename.

Fix downloaded file having no type extension

---

Cargo.lock
Cargo.toml
README.md
wally-registry-backend/Cargo.toml
wally-registry-backend/Dockerfile
wally-registry-backend/README.md
wally-registry-backend/src/auth.rs
wally-registry-frontend/src/pages/Install.mdx

Currently validation of OAuth tokens doesn't validate those tokens originated from our own OAuth app! This PR adds changes to the token verification process to ensure they always originated from our app.
Additionally, due to the time crate, the minimum supported rust version has been bumped to 1.80.0.

Improve validation of OAuth tokens

---

README.md

Removes the defunct link to the Status page for Wally services. https://upliftgames-wally.statuspage.io/

Remove Status page from README

---

Cargo.lock

It will be annoying if we have to rebuild for all of these, so I'm going to bundle them.

Handle cargo dependabot bumps
